### ISSUE TITLE
data_gtfs directory not created on start

### ISSUE THREAD

**Issue by tafflin** [MKuranowski/TokyoGTFS#1]
Hi,
I've tried using your utility to create gtfs from odpt. Am I right to assume that you create GTFS files from json data of stops/routes/timetables provided by odpt?

I have an issue running the utility, I get this error:
```
tafflin@tafflin-ubuntu:~/Documents/tokyo/TokyoGTFS$ python3 -m static.bus create-gtfs
   123 ms [INFO] Main: Getting providers
   161 ms [INFO] Main: Creating helper objects
   161 ms [INFO] Exporter.translations: Opening file
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tafflin/Documents/tokyo/TokyoGTFS/static/bus/__main__.py", line 62, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/tafflin/Documents/tokyo/TokyoGTFS/static/bus/__main__.py", line 54, in main
    ret_code = create_gtfs(ConvertOptions.from_namespace(args))
  File "/home/tafflin/Documents/tokyo/TokyoGTFS/static/bus/main.py", line 27, in create_gtfs
    with SimpleExporter("translations") as translations:
  File "/home/tafflin/Documents/tokyo/TokyoGTFS/static/exporter.py", line 21, in __init__
    self.fileobj = open(self.filepath, "w", encoding="utf-8", newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'data_gtfs/translations.txt'
```

**Comment by MKuranowski** [comment]
It's not the translations.txt file that's missing, it's the `data_gtfs` directory. A simple mkdir should be enough.

**Comment by tafflin** [comment]
@MKuranowski hi and thanks. Same goes to `data_cached` directory
